version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: dating_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: dating_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: 