"""Add firebase_id to messages table

Revision ID: ad434d509367
Revises: c2b5beb307a7
Create Date: 2025-06-26 21:23:15.409530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad434d509367'
down_revision: Union[str, None] = 'b1a2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversations_user1_id_user2_id_key', 'conversations', type_='unique')
    op.drop_index('idx_conversations_last_message', table_name='conversations')
    op.drop_index('idx_conversations_user1', table_name='conversations')
    op.drop_index('idx_conversations_user2', table_name='conversations')
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.drop_constraint('conversations_user2_id_fkey', 'conversations', type_='foreignkey')
    op.drop_constraint('conversations_user1_id_fkey', 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user2_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'users', ['user1_id'], ['id'])
    op.add_column('messages', sa.Column('firebase_id', sa.String(), nullable=True))
    op.drop_index('idx_messages_conversation', table_name='messages')
    op.drop_index('idx_messages_sender', table_name='messages')
    op.drop_index('idx_messages_timestamp', table_name='messages')
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_unique_constraint(None, 'messages', ['firebase_id'])
    op.drop_constraint('messages_sender_id_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_conversation_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    op.drop_index('idx_users_name', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_name', 'users', ['name'], unique=False)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_conversation_id_fkey', 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('messages_sender_id_fkey', 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.create_index('idx_messages_timestamp', 'messages', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index('idx_messages_sender', 'messages', ['sender_id'], unique=False)
    op.create_index('idx_messages_conversation', 'messages', ['conversation_id'], unique=False)
    op.drop_column('messages', 'firebase_id')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key('conversations_user1_id_fkey', 'conversations', 'users', ['user1_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('conversations_user2_id_fkey', 'conversations', 'users', ['user2_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.create_index('idx_conversations_user2', 'conversations', ['user2_id'], unique=False)
    op.create_index('idx_conversations_user1', 'conversations', ['user1_id'], unique=False)
    op.create_index('idx_conversations_last_message', 'conversations', [sa.literal_column('last_message_at DESC')], unique=False)
    op.create_unique_constraint('conversations_user1_id_user2_id_key', 'conversations', ['user1_id', 'user2_id'])
    # ### end Alembic commands ###
