"""Add missing fields to match frontend User model

Revision ID: c2b5beb307a7
Revises: d2783a66bdb2
Create Date: 2025-06-21 20:14:43.731962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2b5beb307a7'
down_revision: Union[str, None] = 'd2783a66bdb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('strikes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'strikes')
    op.drop_column('users', 'state')
    # ### end Alembic commands ###
