"""Add matchmaking fields

Revision ID: d2783a66bdb2
Revises: 8e156c91bee2
Create Date: 2025-06-01 15:02:39.910298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2783a66bdb2'
down_revision: Union[str, None] = '8e156c91bee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('match_score', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('status', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('matches', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('matches', sa.Column('user1_last_active', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('matches', sa.Column('user2_last_active', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('matches', sa.Column('user1_unread_count', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('user2_unread_count', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('user1_status', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('user2_status', sa.String(), nullable=True))
    op.drop_column('matches', 'timestamp')
    op.add_column('swipes', sa.Column('match_score', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('max_distance_km', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_active', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('profile_completed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('profile_image_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('additional_image_urls', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'additional_image_urls')
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'profile_completed')
    op.drop_column('users', 'last_active')
    op.drop_column('users', 'max_distance_km')
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'name')
    op.drop_column('swipes', 'match_score')
    op.add_column('matches', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('matches', 'user2_status')
    op.drop_column('matches', 'user1_status')
    op.drop_column('matches', 'user2_unread_count')
    op.drop_column('matches', 'user1_unread_count')
    op.drop_column('matches', 'user2_last_active')
    op.drop_column('matches', 'user1_last_active')
    op.drop_column('matches', 'last_updated')
    op.drop_column('matches', 'created_at')
    op.drop_column('matches', 'status')
    op.drop_column('matches', 'match_score')
    # ### end Alembic commands ###
